(defpackage #:raylib
  (:use #:common-lisp #:cffi)
  (:export #:init-window
           #:close-window
           #:init-audio-device
           #:close-audio-device
           #:set-target-fps
           #:load-sound
           #:play-sound
           #:load-texture
           #:load-texture-from-image
           #:load-render-texture
           #:gen-image-color
           #:image-draw-pixel
           #:alloc-image
           #:image-flip-vertical
           #:render-texture-texture
           #:begin-texture-mode
           #:end-texture-mode
           #:texture-width
           #:texture-height
           #:window-should-close
           #:begin-drawing
           #:clear-background
           #:end-drawing
           #:is-mouse-button-pressed
           #:is-key-pressed
           #:draw-fps
           #:draw-text
           #:draw-rectangle
           #:get-mouse-position
           #:vector2-x
           #:vector2-y
           #:make-vector2
           #:make-rectangle
           #:load-shader
           #:load-shader-from-memory
           #:draw-texture
           #:draw-texture-pro
           #:draw-line
           #:draw-texture-rec
           #:begin-mode-2d
           #:end-mode-2d
           #:begin-shader-mode
           #:end-shader-mode
           #:make-camera2d
           #:get-frame-time
           #:set-shader-value
           #:set-shader-float
           #:set-shader-vec2
           #:get-shader-location
           #:get-screen-width
           #:get-screen-height
           #:+raywhite+
           #:+red+
           #:+black+
           #:+brown+
           #:+blank+
           #:+blue+
           #:+white+))
